FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache ffmpeg

COPY cloud/api/package.json ./package.json
COPY cloud/api/package-lock.json ./package-lock.json
RUN npm ci

COPY cloud/api/. .
RUN npx prisma generate
RUN npm run build

ENV NODE_ENV=production
EXPOSE 8080

CMD ["npm", "run", "start"]
